import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as fsp from "node:fs/promises";
import * as path from "node:path";

export interface LaunchChildOptions {
  cwd: string;
  jobId: string;
  jobDir: string;
  childSystemPromptPath: string;
  initialPrompt: string;
  forkSessionFile?: string;
}

export async function launchKittyChildPi(options: LaunchChildOptions): Promise<void> {
  const piArgs: string[] = [];
  if (options.forkSessionFile) piArgs.push("--fork", options.forkSessionFile);
  piArgs.push(
    "--append-system-prompt",
    options.childSystemPromptPath,
    "--name",
    `sub ${options.jobId}`,
    options.initialPrompt,
  );

  const piInvocation = getPiInvocation(piArgs);
  const shellLaunch = await prepareInteractiveShellLaunch(options, piInvocation);

  const child = spawn(
    "kitty",
    [
      "--single-instance",
      "--instance-group",
      "i3",
      "--hold",
      "env",
      `PI_SUB_JOB_ID=${options.jobId}`,
      `PI_SUB_JOB_DIR=${options.jobDir}`,
      `PI_SUB_PARENT_CWD=${options.cwd}`,
      "bash",
      "--rcfile",
      shellLaunch.rcFile,
      "-i",
    ],
    {
      cwd: options.cwd,
      detached: true,
      stdio: "ignore",
    },
  );

  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      child.unref();
      resolve();
    }, 500);

    child.once("error", (error) => {
      clearTimeout(timeout);
      reject(error);
    });

    child.once("exit", (code) => {
      if (code === 0 || code === null) return;
      clearTimeout(timeout);
      reject(new Error(`kitty exited immediately with code ${code}`));
    });
  });
}

async function prepareInteractiveShellLaunch(
  options: LaunchChildOptions,
  piInvocation: { command: string; args: string[] },
): Promise<{ rcFile: string }> {
  const rcFile = path.join(options.jobDir, "sub-shell-rc.bash");
  const runScript = path.join(options.jobDir, "run-child-pi.bash");

  await fsp.mkdir(options.jobDir, { recursive: true });
  await fsp.writeFile(runScript, buildRunScript(options.jobId, piInvocation), {
    encoding: "utf8",
    mode: 0o700,
  });
  await fsp.chmod(runScript, 0o700);
  await fsp.writeFile(rcFile, buildShellRc(runScript), { encoding: "utf8", mode: 0o600 });

  return { rcFile };
}

function buildRunScript(jobId: string, piInvocation: { command: string; args: string[] }): string {
  const command = [piInvocation.command, ...piInvocation.args].map(shellQuote).join(" ");
  return `#!/usr/bin/env bash
# Generated by the Pi /sub extension for Delegation Job ${jobId}.
# The interactive parent shell runs this as a foreground job so Ctrl+Z works normally.
${command}
status=$?
printf '\n[sub-agent ${jobId} exited with status %s]\n' "$status"
exit "$status"
`;
}

function buildShellRc(runScript: string): string {
  return `# Generated by the Pi /sub extension.
# Source the user's normal bash startup first, then run the child Pi once from
# PROMPT_COMMAND. Running from the first prompt lets bash put Pi in a foreground
# job-control process group, so Pi's Ctrl+Z can suspend back to this shell.
if [[ -r "$HOME/.bashrc" && "$HOME/.bashrc" != "\${BASH_SOURCE[0]}" ]]; then
  source "$HOME/.bashrc"
fi

__pi_sub_original_prompt_command=\${PROMPT_COMMAND-}
__pi_sub_start_once() {
  PROMPT_COMMAND=$__pi_sub_original_prompt_command
  unset __pi_sub_original_prompt_command
  unset -f __pi_sub_start_once
  ${shellQuote(runScript)}
}
PROMPT_COMMAND=__pi_sub_start_once
`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function getPiInvocation(args: string[]): { command: string; args: string[] } {
  const currentScript = process.argv[1];
  const isBunVirtualScript = currentScript?.startsWith("/$bunfs/root/");
  if (currentScript && !isBunVirtualScript && fs.existsSync(currentScript)) {
    return { command: process.execPath, args: [currentScript, ...args] };
  }

  const execName = path.basename(process.execPath).toLowerCase();
  const isGenericRuntime = /^(node|bun)(\.exe)?$/.test(execName);
  if (!isGenericRuntime) {
    return { command: process.execPath, args };
  }

  return { command: "pi", args };
}
